name: Dev PR Build

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - dev
    types: [opened, synchronize, reopened]

jobs:
  dev-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        repository: "${{ github.event.pull_request.head.repo.full_name }}"
        ref: "${{ github.event.pull_request.head.ref }}"
        fetch-depth: 0
        submodules: recursive
        path: ${{ github.workspace }}/${{ github.run_number }}
        
    - name: Display build info
      run: |
        echo "Building from dev branch"
        echo "Environment: ${{ github.event.inputs.environment || 'development' }}"
        echo "Debug mode: ${{ github.event.inputs.debug || 'false' }}"
        echo "Triggered by: ${{ github.event_name }}"
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name-dev:$(date +%s)
      
    - name: Save Docker image
      run: docker save my-image-name-dev:$(date +%s) -o docker-image-dev.tar
      
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-docker-image-dev-${{ github.run_number }}
        path: docker-image-dev.tar
        
    - name: Display completion message
      run: |
        echo "✅ Dev branch Docker build completed successfully"
        echo "Image built and saved as docker-image-dev.tar"
        echo "Artifact name: flask-application-docker-image-dev-${{ github.run_number }}"
