name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: '30 9 * * 3' # 3:00 PM IST on wednesdays
  - cron: '*/5 * * * *' # 9:00 PM IST on saturdays (15:00 UTC = 20:30 IST)

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event.schedule == '30 9 * * 3' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Save Docker image
      run: docker save my-image-name:$(date +%s) -o docker-image.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-docker-image
        path: docker-image.tar

  alternate-build:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/5 * * * *'

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
      continue-on-error: true
    - name: Fallback to main branch if dev doesn't exist
      if: failure()
      uses: actions/checkout@v4
    - name: Build the Docker image (Alternate)
      run: docker build . --file Dockerfile --tag my-image-name-alt:$(date +%s)
    - name: Save Docker image (Alternate)
      run: docker save my-image-name-alt:$(date +%s) -o docker-image-alt.tar
    - name: Upload Docker image artifact (Alternate)
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-docker-image-alt
        path: docker-image-alt.tar
