name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: '30 9 * * 3' # 3:00 PM IST on wednesdays
  - cron: '00 8 * * 5' # 1:30 PM IST on fridays (15:00 UTC = 20:30 IST)

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event.schedule == '30 9 * * 3' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Save Docker image
      run: docker save my-image-name:$(date +%s) -o docker-image.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-docker-image
        path: docker-image.tar

  alternate-build:
    runs-on: ubuntu-latest
    if: github.event.schedule == '00 8 * * 5'
    env:
      DEV_EX: true

    steps:
    - name: Check if dev branch exists
      id: devcheck
      run: |
        if git ls-remote --heads origin dev | grep -q dev; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    - name: Checkout dev branch
      if: steps.devcheck.outputs.exists == 'true'
      uses: actions/checkout@v4
      with:
        ref: dev
      continue-on-error: true
    - name: Checkout main branch
      if: steps.devcheck.outputs.exists == 'false'
      uses: actions/checkout@v4
    - name: Build the Docker image (Alternate)
      env:
        TIMESTAMP: ${{ github.run_number }}
      run: docker build . --file Dockerfile --tag my-image-name-alt:${{ env.TIMESTAMP }}
    - name: Save Docker image (Alternate)
      env:
        TIMESTAMP: ${{ github.run_number }}
      run: docker save my-image-name-alt:${{ env.TIMESTAMP }} -o docker-image-alt.tar
    - name: Upload Docker image artifact (Alternate)
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-docker-image-alt
        path: docker-image-alt.tar
