name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: '05 09 * * 3' # 2:30 PM IST on wednesdays.  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-$(date +%s)
        path: my-image-name:$(date +%s)
