name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: '30 6 * * 4' # 12:00 PM IST on thursdays  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name-dev:$(date +%s)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: flask-application-$(date +%s)
        path: my-image-name:$(date +%s)
